version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personal_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./personal-tracker-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:9000"
    environment:
      DB_HOST: mysql
      DB_DATABASE: personal_tracker
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      - mysql

  frontend:
    build:
      context: ./personal-tracker-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
